name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Code Verification
      uses: actions/checkout@v4
    - name: Foundry Installation
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly
    - name: Forge Installation
      run: |
        cd hw
        forge install
      id: test
    
    - name: BadBot
      id: problem-1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Exploit
        command: cd hw && forge test --mc ExploitTest --mt test_liquidateHealthyTrove
        timeout: 300
        max-score: 100

    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PROBLEM-1_RESULTS: "${{steps.problem-1.outputs.result}}"
      with:
        runners: problem-1
