name: Autograding Tests
'on':
- push
- repository_dispatch

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Submission
      uses: actions/checkout@v4

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly
    - name: Forge Installation
      run: |
        cd hw
        forge install
      id: test

    - name: Run Foundry Tests for Attack Simulation
      run: |
        forge test --match-path test/exploit.t.sol
      id: run-tests

    - name: Report Autograding Results
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Attack Simulation
        command: forge test --match-path test/exploit.t.sol
        timeout: 300 
        max-score: 100

